// [SampleNote] 홈 인기자료에서 보여주는 예시 노트(읽기전용)
import React,{useMemo}from"react";import{useParams,Link}from"react-router-dom";import MarkdownView from"../components/MarkdownView";
const MAP:Record<string,{title:string;author:string;md:string}>=
{"js-core":{title:"JS 핵심 정리(스코프/클로저/이벤트루프)",author:"dev_huni",md:
"## 요약\n- JS는 렉시컬 스코프를 사용하며, 클로저로 외부 환경을 캡쳐합니다.\n- 이벤트 루프는 콜스택/태스크 큐/마이크로태스크 큐로 구성됩니다.\n\n## 스코프와 클로저\n- 함수가 선언될 때의 환경을 기억합니다.\n- 캡쳐된 변수는 가비지컬렉션으로부터 유지됩니다.\n\n```js\nfunction makeCounter(){\n  let n=0;\n  return ()=>++n;\n}\nconst c=makeCounter();\nconsole.log(c()); // 1\nconsole.log(c()); // 2\n```\n\n## 이벤트 루프\n- 마이크로태스크(Promise.then)가 태스크(setTimeout)보다 먼저 실행\n- 렌더 사이클과의 상호작용\n\n```js\nconsole.log('A');\nqueueMicrotask(()=>console.log('micro'));\nsetTimeout(()=>console.log('timeout'));\nconsole.log('B'); // A, B, micro, timeout\n```\n\n## 체크리스트\n- [ ] 클로저 메모리 누수 방지\n- [ ] 긴 루프는 청크로 나누기(requestIdleCallback 등)\n\n## 예상문제\n1) 클로저가 캡쳐하는 것은 값인가 참조인가?\n2) 마이크로태스크와 태스크의 차이를 설명하라.\n"},
"spring-basic":{title:"Spring 입문(컨테이너/빈/DI/AOP)",author:"spring_begin",md:
"## 핵심 요약\n- IoC 컨테이너는 객체 생명주기를 관리합니다.\n- 생성자 주입을 권장하며 불변성을 선호합니다.\n\n## 컨테이너와 Bean\n- ApplicationContext, BeanDefinition, Scope(singleton/prototype)\n\n## DI 패턴\n- 생성자 주입 vs 필드/세터 주입\n- `@Configuration` + `@Bean`, 컴포넌트 스캔\n\n## AOP\n- 횡단 관심사(트랜잭션/로깅/보안) 분리\n- 프록시 기반, Advice/Pointcut/JoinPoint\n\n## 실습 코드\n```java\n@Service\npublic class OrderService {\n  private final PayClient pay;\n  public OrderService(PayClient pay){this.pay=pay;}\n}\n```\n\n## 예상문제\n1) 생성자 주입이 가지는 이점 3가지\n2) 프록시 기반 AOP의 동작 원리\n"},
"react-summary":{title:"React 요약(렌더링/상태/성능)",author:"rnlee",md:
"## 요약\n- 렌더링은 순수함수 규칙을 지키고, 상태는 위로 끌어올리기\n- 메모이제이션은 병목에서만 최소 적용\n\n## 렌더링 모델\n- props/state 변경 → render → commit\n- strict mode에서는 일부 이펙트가 두 번 호출 가능\n\n## 상태 관리\n- 리프트업/컨텍스트, 서버 상태는 쿼리 라이브러리 권장\n\n## 성능\n- `useMemo/useCallback`은 의존성 정확히, 불필요 남용 금지\n- 리스트는 key 안정성 확보, 가상화 고려\n\n## 예제\n```tsx\nfunction List({items}:{items:string[]}){\n  return <ul>{items.map(it=><li key={it}>{it}</li>)}</ul>\n}\n```\n\n## 예상문제\n1) 리액트에서 재조정(reconciliation)이란?\n2) 메모이제이션이 역효과를 내는 경우\n"},
"sql-grammar":{title:"SQL 핵심 문법(윈도우/집계/서브쿼리)",author:"sqldream",md:
"## 요약\n- 윈도우 함수로 누적/순위/이동평균을 효율적으로 계산\n\n## 윈도우 함수\n```sql\nSELECT user_id,\n       SUM(amount) OVER(PARTITION BY user_id ORDER BY ts) AS cum_amount,\n       ROW_NUMBER() OVER(PARTITION BY user_id ORDER BY ts) AS rn\nFROM payments;\n```\n\n## 집계와 서브쿼리\n- 스칼라/상관/파생 테이블 차이\n\n## 안티패턴\n- N+1 서브쿼리, 불필요한 DISTINCT\n\n## 예상문제\n1) RANK() vs DENSE_RANK() 차이\n2) WINDOW FRAME의 기본 범위 의미\n"},
"network":{title:"네트워크(OSI/TCP·IP/서브넷/VLAN) 한눈정리",author:"net_lab",md:
"## 요약\n- L2 스위칭과 L3 라우팅의 차이 명확히 이해\n\n## OSI vs TCP/IP\n- 표현/세션은 TCP/IP에서 애플리케이션으로 통합\n\n## 서브넷팅\n```text\n/24 -> 256 IP (호스트 254)\n/26 -> 64 IP (호스트 62)\n```\n- CIDR, 브로드캐스트/네트워크 주소 구분\n\n## VLAN\n- 802.1Q 태깅, 트렁크/액세스 포트\n\n## 예상문제\n1) ARP의 역할\n2) TCP 3-way handshake 절차\n"}};
export default function SampleNote(){const{slug}=useParams();const note=useMemo(()=>MAP[slug||""],[slug]);if(!note)return(<div className="container section"><div className="card">예시 노트를 찾을 수 없습니다. <Link to="/">홈으로</Link></div></div>);
const md=`# ${note.title}\n\n> 작성자: **${note.author}** · 예시 노트 (읽기 전용)\n\n${note.md}\n\n---\n\n### 참고 자료\n- MDN, Spring Docs, React Docs, PostgreSQL Docs\n- 더 자세한 내용은 각 상세 페이지에서 확인하세요.`;return(<div className="container section"><div style={{marginBottom:12,display:"flex",gap:8,alignItems:"center",justifyContent:"space-between"}}><Link to="/" className="btn">← 홈</Link><div className="muted" style={{fontSize:13}}>샘플 뷰 · 읽기 전용</div></div><div className="card" style={{padding:0}}><MarkdownView content={md}/></div></div>)}
